# Generated by Django 4.1.5 on 2023-01-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='RideUser',
        ),
        migrations.AlterField(
            model_name='driver',
            name='special_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_requests',
            field=models.TextField(null=True),
        ),
    ]
