# Generated by Django 4.1.5 on 2023-02-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_rename_user_rideuser_alter_driver_special_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharers',
            field=models.ManyToManyField(related_name='shared_rides', to='ride.rideuser'),
        ),
    ]
