# Generated by Django 4.1.5 on 2023-02-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_alter_ride_sharer_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharers',
            field=models.ManyToManyField(related_name='shared_rides', to='ride.rideuser'),
        ),
    ]
