# Generated by Django 4.1.5 on 2023-02-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_rename_num_pax_ride_num_pax_owner_ride_num_pax_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer_num',
            field=models.JSONField(null=True),
        ),
    ]
