# Generated by Django 4.1.5 on 2023-02-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_alter_ride_special_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer_num',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_requests',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
