# Generated by Django 4.1.5 on 2023-02-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_alter_ride_sharer_num_alter_ride_special_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='special_info',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
