# Generated by Django 4.1.5 on 2023-02-02 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_alter_ride_sharers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='num_pax',
            new_name='num_pax_owner',
        ),
        migrations.AddField(
            model_name='ride',
            name='num_pax_total',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
            preserve_default=False,
        ),
    ]
