# Generated by Django 4.1.5 on 2023-02-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_alter_driver_special_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer_num',
            field=models.JSONField(default=dict),
        ),
    ]
